##
## Copyright (c) 2026 Oracle and/or its affiliates.
## Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/
##

"""
ORDS Database API

A Database Management and Monitoring REST API embedded into Oracle REST Data Services. The behaviour and response structure of these services are dictated by the database instance used at runtime. Please refer to Oracle Database Documentation https://docs.oracle.com/en/database/oracle/oracle-database/index.html for more detailed information on the particular version of Oracle Database used. Please also refer to Oracle REST Data Services product documentation to gain a full understanding of the REST capabilities provided. This includes, but is not limited to, resource security, connection pooling, pagination and data filtering.

The version of the OpenAPI document is defined by oracle_vecdb.version.ORDS_RELEASE_VERSION.
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictStr
from typing_extensions import Annotated
from oracle_vecdb.services.ords.models.query_vectors200_response import (
    QueryVectors200Response,
)
from oracle_vecdb.services.ords.models.query_vectors_request import (
    QueryVectorsRequest,
)

from oracle_vecdb.services.ords.api_client import ApiClient, RequestSerialized
from oracle_vecdb.services.ords.api_response import ApiResponse
from oracle_vecdb.services.ords.rest import RESTResponseType


class VectorDatabaseVectorSearchApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client

    @validate_call
    def query_vectors(
        self,
        vector_table_name: Annotated[
            StrictStr, Field(description="The name of the vector table.")
        ],
        query_vectors_request: QueryVectorsRequest,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)],
            ],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> QueryVectors200Response:
        """Perform a vector similarity search over the specified vector table.

        Perform a vector similarity search using text, a vector or an ID returning the most similar records as well as their distance.

        :param vector_table_name: The name of the vector table. (required)
        :type vector_table_name: str
        :param query_vectors_request: (required)
        :type query_vectors_request: QueryVectorsRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._query_vectors_serialize(
            vector_table_name=vector_table_name,
            query_vectors_request=query_vectors_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "QueryVectors200Response",
            "400": "ORDSErrorResponse",
            "404": "ORDSErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param, _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data

    @validate_call
    def query_vectors_with_http_info(
        self,
        vector_table_name: Annotated[
            StrictStr, Field(description="The name of the vector table.")
        ],
        query_vectors_request: QueryVectorsRequest,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)],
            ],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[QueryVectors200Response]:
        """Perform a vector similarity search over the specified vector table.

        Perform a vector similarity search using text, a vector or an ID returning the most similar records as well as their distance.

        :param vector_table_name: The name of the vector table. (required)
        :type vector_table_name: str
        :param query_vectors_request: (required)
        :type query_vectors_request: QueryVectorsRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._query_vectors_serialize(
            vector_table_name=vector_table_name,
            query_vectors_request=query_vectors_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "QueryVectors200Response",
            "400": "ORDSErrorResponse",
            "404": "ORDSErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param, _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )

    @validate_call
    def query_vectors_without_preload_content(
        self,
        vector_table_name: Annotated[
            StrictStr, Field(description="The name of the vector table.")
        ],
        query_vectors_request: QueryVectorsRequest,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)],
            ],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Perform a vector similarity search over the specified vector table.

        Perform a vector similarity search using text, a vector or an ID returning the most similar records as well as their distance.

        :param vector_table_name: The name of the vector table. (required)
        :type vector_table_name: str
        :param query_vectors_request: (required)
        :type query_vectors_request: QueryVectorsRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._query_vectors_serialize(
            vector_table_name=vector_table_name,
            query_vectors_request=query_vectors_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "QueryVectors200Response",
            "400": "ORDSErrorResponse",
            "404": "ORDSErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param, _request_timeout=_request_timeout
        )
        return response_data.response

    def _query_vectors_serialize(
        self,
        vector_table_name,
        query_vectors_request,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {}

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str,
            Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]],
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if vector_table_name is not None:
            _path_params["vector_table_name"] = vector_table_name
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter
        if query_vectors_request is not None:
            _body_params = query_vectors_request

        # set the HTTP header `Accept`
        if "Accept" not in _header_params:
            _header_params["Accept"] = self.api_client.select_header_accept(
                ["application/json", "application/problem+json"]
            )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params["Content-Type"] = _content_type
        else:
            _default_content_type = self.api_client.select_header_content_type(
                ["application/json"]
            )
            if _default_content_type is not None:
                _header_params["Content-Type"] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
            "OAuth2",
            "OAuth2",
            "OAuth2",
            "BasicAuth",
            "BearerAuth",
        ]

        return self.api_client.param_serialize(
            method="POST",
            resource_path="/vecdb/vector-tables/{vector_table_name}/query",
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth,
        )
