# coding: utf-8
##
## Copyright (c) 2026 Oracle and/or its affiliates.
## Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/
##


"""
ORDS Database API

A Database Management and Monitoring REST API embedded into Oracle REST Data Services. The behaviour and response structure of these services are dictated by the database instance used at runtime. Please refer to Oracle Database Documentation https://docs.oracle.com/en/database/oracle/oracle-database/index.html for more detailed information on the particular version of Oracle Database used. Please also refer to Oracle REST Data Services product documentation to gain a full understanding of the REST capabilities provided. This includes, but is not limited to, resource security, connection pooling, pagination and data filtering.

The version of the OpenAPI document is defined by oracle_vecdb.version.ORDS_RELEASE_VERSION.
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from oracle_vecdb.services.ords.models.load_model_request_model_params import (
    LoadModelRequestModelParams,
)
from oracle_vecdb.services.ords.models.vector_debug_flags import (
    VectorDebugFlags,
)
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python


class LoadModelRequest(BaseModel):
    """
    LoadModelRequest
    """  # noqa: E501

    model_name: StrictStr = Field(
        description="The name of the model.", alias="modelName"
    )
    url: StrictStr = Field(description="The PAR URL of the model.")
    model_params: Optional[LoadModelRequestModelParams] = Field(
        default=None, alias="modelParams"
    )
    debug_flags: Optional[VectorDebugFlags] = Field(
        default=None, alias="debugFlags"
    )
    __properties: ClassVar[List[str]] = [
        "modelName",
        "url",
        "modelParams",
        "debugFlags",
    ]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of LoadModelRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of model_params
        if self.model_params:
            _dict["modelParams"] = self.model_params.to_dict()
        # override the default output from pydantic by calling `to_dict()` of debug_flags
        if self.debug_flags:
            _dict["debugFlags"] = self.debug_flags.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of LoadModelRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "modelName": obj.get("modelName"),
                "url": obj.get("url"),
                "modelParams": (
                    LoadModelRequestModelParams.from_dict(obj["modelParams"])
                    if obj.get("modelParams") is not None
                    else None
                ),
                "debugFlags": (
                    VectorDebugFlags.from_dict(obj["debugFlags"])
                    if obj.get("debugFlags") is not None
                    else None
                ),
            }
        )
        return _obj
