# coding: utf-8
##
## Copyright (c) 2026 Oracle and/or its affiliates.
## Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/
##


"""
ORDS Database API

A Database Management and Monitoring REST API embedded into Oracle REST Data Services. The behaviour and response structure of these services are dictated by the database instance used at runtime. Please refer to Oracle Database Documentation https://docs.oracle.com/en/database/oracle/oracle-database/index.html for more detailed information on the particular version of Oracle Database used. Please also refer to Oracle REST Data Services product documentation to gain a full understanding of the REST capabilities provided. This includes, but is not limited to, resource security, connection pooling, pagination and data filtering.

The version of the OpenAPI document is defined by oracle_vecdb.version.ORDS_RELEASE_VERSION.
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    StrictInt,
    StrictStr,
    field_validator,
)
from typing import Any, ClassVar, Dict, List, Optional
from oracle_vecdb.services.ords.models.link_relation import LinkRelation
from oracle_vecdb.services.ords.models.vec_db_table_base_no_links_embed_params import (
    VecDBTableBaseNoLinksEmbedParams,
)
from oracle_vecdb.services.ords.models.vec_db_table_base_no_links_indexes import (
    VecDBTableBaseNoLinksIndexes,
)
from oracle_vecdb.services.ords.models.vector_index_params import (
    VectorIndexParams,
)
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python


class VecDBTableItem(BaseModel):
    """
    VecDBTableItem
    """  # noqa: E501

    table_name: Optional[StrictStr] = Field(
        default=None, description="The name of the vector table."
    )
    comment: Optional[StrictStr] = Field(
        default=None, description="Table comment."
    )
    annotations: Optional[Dict[str, Any]] = Field(
        default=None, description="User metadata attached to the table."
    )
    vector_type: Optional[StrictStr] = None
    vector_table_type: Optional[StrictStr] = Field(
        default=None, description="Creation mode of the table."
    )
    embed_params: Optional[VecDBTableBaseNoLinksEmbedParams] = None
    index_params: Optional[VectorIndexParams] = None
    owner: Optional[StrictStr] = None
    indexes: Optional[VecDBTableBaseNoLinksIndexes] = None
    status: Optional[StrictStr] = Field(
        default=None, description="Population status of the vector table."
    )
    stats: Optional[Dict[str, Any]] = Field(
        default=None, description="Statistics of the vector table."
    )
    created: Optional[datetime] = Field(
        default=None, description="Creation timestamp of the vector table."
    )
    updated: Optional[datetime] = Field(
        default=None, description="Update timestamp of the vector table."
    )
    description: Optional[StrictStr] = Field(
        default=None, description="Table description."
    )
    auto_generate_id: Optional[StrictInt] = Field(
        default=None, description="1 if ID defaults to SYS_GUID(), otherwise 0."
    )
    links: Optional[List[LinkRelation]] = None
    __properties: ClassVar[List[str]] = [
        "table_name",
        "comment",
        "annotations",
        "vector_type",
        "vector_table_type",
        "embed_params",
        "index_params",
        "owner",
        "indexes",
        "status",
        "stats",
        "created",
        "updated",
        "description",
        "auto_generate_id",
        "links",
    ]

    @field_validator("vector_type")
    def vector_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["dense"]):
            raise ValueError("must be one of enum values ('dense')")
        return value

    @field_validator("vector_table_type")
    def vector_table_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["BYOV", "MODEL"]):
            raise ValueError("must be one of enum values ('BYOV', 'MODEL')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of VecDBTableItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of embed_params
        if self.embed_params:
            _dict["embed_params"] = self.embed_params.to_dict()
        # override the default output from pydantic by calling `to_dict()` of index_params
        if self.index_params:
            _dict["index_params"] = self.index_params.to_dict()
        # override the default output from pydantic by calling `to_dict()` of indexes
        if self.indexes:
            _dict["indexes"] = self.indexes.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in links (list)
        _items = []
        if self.links:
            for _item_links in self.links:
                if _item_links:
                    _items.append(_item_links.to_dict())
            _dict["links"] = _items
        # set to None if comment (nullable) is None
        # and model_fields_set contains the field
        if self.comment is None and "comment" in self.model_fields_set:
            _dict["comment"] = None

        # set to None if annotations (nullable) is None
        # and model_fields_set contains the field
        if self.annotations is None and "annotations" in self.model_fields_set:
            _dict["annotations"] = None

        # set to None if embed_params (nullable) is None
        # and model_fields_set contains the field
        if (
            self.embed_params is None
            and "embed_params" in self.model_fields_set
        ):
            _dict["embed_params"] = None

        # set to None if indexes (nullable) is None
        # and model_fields_set contains the field
        if self.indexes is None and "indexes" in self.model_fields_set:
            _dict["indexes"] = None

        # set to None if stats (nullable) is None
        # and model_fields_set contains the field
        if self.stats is None and "stats" in self.model_fields_set:
            _dict["stats"] = None

        # set to None if updated (nullable) is None
        # and model_fields_set contains the field
        if self.updated is None and "updated" in self.model_fields_set:
            _dict["updated"] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict["description"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of VecDBTableItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "table_name": obj.get("table_name"),
                "comment": obj.get("comment"),
                "annotations": obj.get("annotations"),
                "vector_type": obj.get("vector_type"),
                "vector_table_type": obj.get("vector_table_type"),
                "embed_params": (
                    VecDBTableBaseNoLinksEmbedParams.from_dict(
                        obj["embed_params"]
                    )
                    if obj.get("embed_params") is not None
                    else None
                ),
                "index_params": (
                    VectorIndexParams.from_dict(obj["index_params"])
                    if obj.get("index_params") is not None
                    else None
                ),
                "owner": obj.get("owner"),
                "indexes": (
                    VecDBTableBaseNoLinksIndexes.from_dict(obj["indexes"])
                    if obj.get("indexes") is not None
                    else None
                ),
                "status": obj.get("status"),
                "stats": obj.get("stats"),
                "created": obj.get("created"),
                "updated": obj.get("updated"),
                "description": obj.get("description"),
                "auto_generate_id": obj.get("auto_generate_id"),
                "links": (
                    [LinkRelation.from_dict(_item) for _item in obj["links"]]
                    if obj.get("links") is not None
                    else None
                ),
            }
        )
        return _obj
