# coding: utf-8
##
## Copyright (c) 2026 Oracle and/or its affiliates.
## Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/
##


"""
ORDS Database API

A Database Management and Monitoring REST API embedded into Oracle REST Data Services. The behaviour and response structure of these services are dictated by the database instance used at runtime. Please refer to Oracle Database Documentation https://docs.oracle.com/en/database/oracle/oracle-database/index.html for more detailed information on the particular version of Oracle Database used. Please also refer to Oracle REST Data Services product documentation to gain a full understanding of the REST capabilities provided. This includes, but is not limited to, resource security, connection pooling, pagination and data filtering.

The version of the OpenAPI document is defined by oracle_vecdb.version.ORDS_RELEASE_VERSION.
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python


class VecDBTableNoLinksIndexParamsAdvancedParams(BaseModel):
    """
    VecDBTableNoLinksIndexParamsAdvancedParams
    """  # noqa: E501

    partitions: Optional[Union[StrictFloat, StrictInt]] = None
    ef_construction: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None, alias="efConstruction"
    )
    neighbors: Optional[Union[StrictFloat, StrictInt]] = None
    __properties: ClassVar[List[str]] = [
        "partitions",
        "efConstruction",
        "neighbors",
    ]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of VecDBTableNoLinksIndexParamsAdvancedParams from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if partitions (nullable) is None
        # and model_fields_set contains the field
        if self.partitions is None and "partitions" in self.model_fields_set:
            _dict["partitions"] = None

        # set to None if ef_construction (nullable) is None
        # and model_fields_set contains the field
        if (
            self.ef_construction is None
            and "ef_construction" in self.model_fields_set
        ):
            _dict["efConstruction"] = None

        # set to None if neighbors (nullable) is None
        # and model_fields_set contains the field
        if self.neighbors is None and "neighbors" in self.model_fields_set:
            _dict["neighbors"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of VecDBTableNoLinksIndexParamsAdvancedParams from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "partitions": obj.get("partitions"),
                "efConstruction": obj.get("efConstruction"),
                "neighbors": obj.get("neighbors"),
            }
        )
        return _obj
