# coding: utf-8
##
## Copyright (c) 2026 Oracle and/or its affiliates.
## Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/
##


"""
ORDS Database API

A Database Management and Monitoring REST API embedded into Oracle REST Data Services. The behaviour and response structure of these services are dictated by the database instance used at runtime. Please refer to Oracle Database Documentation https://docs.oracle.com/en/database/oracle/oracle-database/index.html for more detailed information on the particular version of Oracle Database used. Please also refer to Oracle REST Data Services product documentation to gain a full understanding of the REST capabilities provided. This includes, but is not limited to, resource security, connection pooling, pagination and data filtering.

The version of the OpenAPI document is defined by oracle_vecdb.version.ORDS_RELEASE_VERSION.
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python


class VectorDebugFlags(BaseModel):
    """
    Debug flags to be used to trace vector modules
    """  # noqa: E501

    vector_index: Optional[StrictStr] = Field(
        default=None, alias="VECTOR_INDEX"
    )
    vector_index_neighbor_graph: Optional[StrictStr] = Field(
        default=None, alias="VECTOR_INDEX_NEIGHBOR_GRAPH"
    )
    vector_index_neighbor_graph_build: Optional[StrictStr] = Field(
        default=None, alias="VECTOR_INDEX_NEIGHBOR_GRAPH_BUILD"
    )
    vector_index_neighbor_graph_mem: Optional[StrictStr] = Field(
        default=None, alias="VECTOR_INDEX_NEIGHBOR_GRAPH_MEM"
    )
    vector_index_neighbor_graph_search: Optional[StrictStr] = Field(
        default=None, alias="VECTOR_INDEX_NEIGHBOR_GRAPH_SEARCH"
    )
    vector_index_neighbor_graph_appchng: Optional[StrictStr] = Field(
        default=None, alias="VECTOR_INDEX_NEIGHBOR_GRAPH_APPCHNG"
    )
    vector_index_neighbor_graph_stats: Optional[StrictStr] = Field(
        default=None, alias="VECTOR_INDEX_NEIGHBOR_GRAPH_STATS"
    )
    vector_index_neighbor_partitions: Optional[StrictStr] = Field(
        default=None, alias="VECTOR_INDEX_NEIGHBOR_PARTITIONS"
    )
    vector_index_fixed_view: Optional[StrictStr] = Field(
        default=None, alias="VECTOR_INDEX_FIXED_VIEW"
    )
    vecidx_trans: Optional[StrictStr] = Field(
        default=None, alias="VECIDX_TRANS"
    )
    vecidx_trans_com: Optional[StrictStr] = Field(
        default=None, alias="VECIDX_TRANS_COM"
    )
    vecidx_trans_pj: Optional[StrictStr] = Field(
        default=None, alias="VECIDX_TRANS_PJ"
    )
    vecidx_trans_pj_dwngrd: Optional[StrictStr] = Field(
        default=None, alias="VECIDX_TRANS_PJ_DWNGRD"
    )
    vecidx_trans_pj_grow: Optional[StrictStr] = Field(
        default=None, alias="VECIDX_TRANS_PJ_GROW"
    )
    vecidx_trans_sj: Optional[StrictStr] = Field(
        default=None, alias="VECIDX_TRANS_SJ"
    )
    vecidx_trans_sj_bg: Optional[StrictStr] = Field(
        default=None, alias="VECIDX_TRANS_SJ_BG"
    )
    vec_index_calibration: Optional[StrictStr] = Field(
        default=None, alias="VEC_INDEX_CALIBRATION"
    )
    vector_trace: Optional[StrictStr] = Field(
        default=None, alias="VECTOR_TRACE"
    )
    __properties: ClassVar[List[str]] = [
        "VECTOR_INDEX",
        "VECTOR_INDEX_NEIGHBOR_GRAPH",
        "VECTOR_INDEX_NEIGHBOR_GRAPH_BUILD",
        "VECTOR_INDEX_NEIGHBOR_GRAPH_MEM",
        "VECTOR_INDEX_NEIGHBOR_GRAPH_SEARCH",
        "VECTOR_INDEX_NEIGHBOR_GRAPH_APPCHNG",
        "VECTOR_INDEX_NEIGHBOR_GRAPH_STATS",
        "VECTOR_INDEX_NEIGHBOR_PARTITIONS",
        "VECTOR_INDEX_FIXED_VIEW",
        "VECIDX_TRANS",
        "VECIDX_TRANS_COM",
        "VECIDX_TRANS_PJ",
        "VECIDX_TRANS_PJ_DWNGRD",
        "VECIDX_TRANS_PJ_GROW",
        "VECIDX_TRANS_SJ",
        "VECIDX_TRANS_SJ_BG",
        "VEC_INDEX_CALIBRATION",
        "VECTOR_TRACE",
    ]

    @field_validator("vector_index")
    def vector_index_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["low", "medium", "high"]):
            raise ValueError(
                "must be one of enum values ('low', 'medium', 'high')"
            )
        return value

    @field_validator("vector_index_neighbor_graph")
    def vector_index_neighbor_graph_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["low", "medium", "high"]):
            raise ValueError(
                "must be one of enum values ('low', 'medium', 'high')"
            )
        return value

    @field_validator("vector_index_neighbor_graph_build")
    def vector_index_neighbor_graph_build_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["low", "medium", "high"]):
            raise ValueError(
                "must be one of enum values ('low', 'medium', 'high')"
            )
        return value

    @field_validator("vector_index_neighbor_graph_mem")
    def vector_index_neighbor_graph_mem_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["low", "medium", "high"]):
            raise ValueError(
                "must be one of enum values ('low', 'medium', 'high')"
            )
        return value

    @field_validator("vector_index_neighbor_graph_search")
    def vector_index_neighbor_graph_search_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["low", "medium", "high"]):
            raise ValueError(
                "must be one of enum values ('low', 'medium', 'high')"
            )
        return value

    @field_validator("vector_index_neighbor_graph_appchng")
    def vector_index_neighbor_graph_appchng_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["low", "medium", "high"]):
            raise ValueError(
                "must be one of enum values ('low', 'medium', 'high')"
            )
        return value

    @field_validator("vector_index_neighbor_graph_stats")
    def vector_index_neighbor_graph_stats_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["low", "medium", "high"]):
            raise ValueError(
                "must be one of enum values ('low', 'medium', 'high')"
            )
        return value

    @field_validator("vector_index_neighbor_partitions")
    def vector_index_neighbor_partitions_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["low", "medium", "high"]):
            raise ValueError(
                "must be one of enum values ('low', 'medium', 'high')"
            )
        return value

    @field_validator("vector_index_fixed_view")
    def vector_index_fixed_view_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["low", "medium", "high"]):
            raise ValueError(
                "must be one of enum values ('low', 'medium', 'high')"
            )
        return value

    @field_validator("vecidx_trans")
    def vecidx_trans_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["low", "medium", "high"]):
            raise ValueError(
                "must be one of enum values ('low', 'medium', 'high')"
            )
        return value

    @field_validator("vecidx_trans_com")
    def vecidx_trans_com_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["low", "medium", "high"]):
            raise ValueError(
                "must be one of enum values ('low', 'medium', 'high')"
            )
        return value

    @field_validator("vecidx_trans_pj")
    def vecidx_trans_pj_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["low", "medium", "high"]):
            raise ValueError(
                "must be one of enum values ('low', 'medium', 'high')"
            )
        return value

    @field_validator("vecidx_trans_pj_dwngrd")
    def vecidx_trans_pj_dwngrd_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["low", "medium", "high"]):
            raise ValueError(
                "must be one of enum values ('low', 'medium', 'high')"
            )
        return value

    @field_validator("vecidx_trans_pj_grow")
    def vecidx_trans_pj_grow_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["low", "medium", "high"]):
            raise ValueError(
                "must be one of enum values ('low', 'medium', 'high')"
            )
        return value

    @field_validator("vecidx_trans_sj")
    def vecidx_trans_sj_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["low", "medium", "high"]):
            raise ValueError(
                "must be one of enum values ('low', 'medium', 'high')"
            )
        return value

    @field_validator("vecidx_trans_sj_bg")
    def vecidx_trans_sj_bg_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["low", "medium", "high"]):
            raise ValueError(
                "must be one of enum values ('low', 'medium', 'high')"
            )
        return value

    @field_validator("vec_index_calibration")
    def vec_index_calibration_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["low", "medium", "high"]):
            raise ValueError(
                "must be one of enum values ('low', 'medium', 'high')"
            )
        return value

    @field_validator("vector_trace")
    def vector_trace_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["low", "medium", "high"]):
            raise ValueError(
                "must be one of enum values ('low', 'medium', 'high')"
            )
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of VectorDebugFlags from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of VectorDebugFlags from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "VECTOR_INDEX": obj.get("VECTOR_INDEX"),
                "VECTOR_INDEX_NEIGHBOR_GRAPH": obj.get(
                    "VECTOR_INDEX_NEIGHBOR_GRAPH"
                ),
                "VECTOR_INDEX_NEIGHBOR_GRAPH_BUILD": obj.get(
                    "VECTOR_INDEX_NEIGHBOR_GRAPH_BUILD"
                ),
                "VECTOR_INDEX_NEIGHBOR_GRAPH_MEM": obj.get(
                    "VECTOR_INDEX_NEIGHBOR_GRAPH_MEM"
                ),
                "VECTOR_INDEX_NEIGHBOR_GRAPH_SEARCH": obj.get(
                    "VECTOR_INDEX_NEIGHBOR_GRAPH_SEARCH"
                ),
                "VECTOR_INDEX_NEIGHBOR_GRAPH_APPCHNG": obj.get(
                    "VECTOR_INDEX_NEIGHBOR_GRAPH_APPCHNG"
                ),
                "VECTOR_INDEX_NEIGHBOR_GRAPH_STATS": obj.get(
                    "VECTOR_INDEX_NEIGHBOR_GRAPH_STATS"
                ),
                "VECTOR_INDEX_NEIGHBOR_PARTITIONS": obj.get(
                    "VECTOR_INDEX_NEIGHBOR_PARTITIONS"
                ),
                "VECTOR_INDEX_FIXED_VIEW": obj.get("VECTOR_INDEX_FIXED_VIEW"),
                "VECIDX_TRANS": obj.get("VECIDX_TRANS"),
                "VECIDX_TRANS_COM": obj.get("VECIDX_TRANS_COM"),
                "VECIDX_TRANS_PJ": obj.get("VECIDX_TRANS_PJ"),
                "VECIDX_TRANS_PJ_DWNGRD": obj.get("VECIDX_TRANS_PJ_DWNGRD"),
                "VECIDX_TRANS_PJ_GROW": obj.get("VECIDX_TRANS_PJ_GROW"),
                "VECIDX_TRANS_SJ": obj.get("VECIDX_TRANS_SJ"),
                "VECIDX_TRANS_SJ_BG": obj.get("VECIDX_TRANS_SJ_BG"),
                "VEC_INDEX_CALIBRATION": obj.get("VEC_INDEX_CALIBRATION"),
                "VECTOR_TRACE": obj.get("VECTOR_TRACE"),
            }
        )
        return _obj
