# coding: utf-8
##
## Copyright (c) 2026 Oracle and/or its affiliates.
## Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/
##


"""
ORDS Database API

A Database Management and Monitoring REST API embedded into Oracle REST Data Services. The behaviour and response structure of these services are dictated by the database instance used at runtime. Please refer to Oracle Database Documentation https://docs.oracle.com/en/database/oracle/oracle-database/index.html for more detailed information on the particular version of Oracle Database used. Please also refer to Oracle REST Data Services product documentation to gain a full understanding of the REST capabilities provided. This includes, but is not limited to, resource security, connection pooling, pagination and data filtering.

The version of the OpenAPI document is defined by oracle_vecdb.version.ORDS_RELEASE_VERSION.
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from oracle_vecdb.services.ords.models.vector_index_params_metadata_index_params import (
    VectorIndexParamsMetadataIndexParams,
)
from oracle_vecdb.services.ords.models.vector_index_params_vector_index_params import (
    VectorIndexParamsVectorIndexParams,
)
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python


class VectorIndexParams(BaseModel):
    """
    Nested index configuration for vector and metadata indexes.
    """  # noqa: E501

    vector_index_params: Optional[VectorIndexParamsVectorIndexParams] = None
    metadata_index_params: Optional[VectorIndexParamsMetadataIndexParams] = None
    parallel_creation: Optional[Annotated[int, Field(strict=True, ge=1)]] = (
        Field(
            default=None,
            description="Parallel DDL degree for vector and metadata index operations.",
        )
    )
    index_type: Optional[StrictStr] = Field(
        default=None,
        description="Action scope for rebuild and drop operations.",
    )
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = [
        "vector_index_params",
        "metadata_index_params",
        "parallel_creation",
        "index_type",
    ]

    @field_validator("index_type")
    def index_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["vector", "metadata", "all"]):
            raise ValueError(
                "must be one of enum values ('vector', 'metadata', 'all')"
            )
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of VectorIndexParams from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set(
            [
                "additional_properties",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of vector_index_params
        if self.vector_index_params:
            _dict["vector_index_params"] = self.vector_index_params.to_dict()
        # override the default output from pydantic by calling `to_dict()` of metadata_index_params
        if self.metadata_index_params:
            _dict["metadata_index_params"] = (
                self.metadata_index_params.to_dict()
            )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if parallel_creation (nullable) is None
        # and model_fields_set contains the field
        if (
            self.parallel_creation is None
            and "parallel_creation" in self.model_fields_set
        ):
            _dict["parallel_creation"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of VectorIndexParams from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "vector_index_params": (
                    VectorIndexParamsVectorIndexParams.from_dict(
                        obj["vector_index_params"]
                    )
                    if obj.get("vector_index_params") is not None
                    else None
                ),
                "metadata_index_params": (
                    VectorIndexParamsMetadataIndexParams.from_dict(
                        obj["metadata_index_params"]
                    )
                    if obj.get("metadata_index_params") is not None
                    else None
                ),
                "parallel_creation": obj.get("parallel_creation"),
                "index_type": obj.get("index_type"),
            }
        )
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj
