# coding: utf-8
##
## Copyright (c) 2026 Oracle and/or its affiliates.
## Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/
##


"""
ORDS Database API

A Database Management and Monitoring REST API embedded into Oracle REST Data Services. The behaviour and response structure of these services are dictated by the database instance used at runtime. Please refer to Oracle Database Documentation https://docs.oracle.com/en/database/oracle/oracle-database/index.html for more detailed information on the particular version of Oracle Database used. Please also refer to Oracle REST Data Services product documentation to gain a full understanding of the REST capabilities provided. This includes, but is not limited to, resource security, connection pooling, pagination and data filtering.

The version of the OpenAPI document is defined by oracle_vecdb.version.ORDS_RELEASE_VERSION.
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    StrictBool,
    StrictFloat,
    StrictInt,
    StrictStr,
    field_validator,
)
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from oracle_vecdb.services.ords.models.vector_index_params_vector_index_params_distribute_params import (
    VectorIndexParamsVectorIndexParamsDistributeParams,
)
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python


class VectorIndexParamsVectorIndexParams(BaseModel):
    """
    Vector index settings such as organization, distance metric, distributed HNSW, scalar quantization, and advanced parameters.
    """  # noqa: E501

    auto_index: Optional[StrictBool] = Field(
        default=None, description="Enables vector index creation or management."
    )
    organization: Optional[StrictStr] = None
    distance_metric: Optional[StrictStr] = None
    accuracy: Optional[Annotated[int, Field(le=100, strict=True, ge=0)]] = None
    online_build: Optional[StrictBool] = None
    quantization_type: Optional[StrictStr] = None
    compression_ratio: Optional[Union[StrictFloat, StrictInt]] = None
    distribute_params: Optional[
        VectorIndexParamsVectorIndexParamsDistributeParams
    ] = None
    advanced_params: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Index-family-specific options such as partitions, neighbors, efConstruction, rescore_factor, or algorithm.",
    )
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = [
        "auto_index",
        "organization",
        "distance_metric",
        "accuracy",
        "online_build",
        "quantization_type",
        "compression_ratio",
        "distribute_params",
        "advanced_params",
    ]

    @field_validator("organization")
    def organization_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["PARTITIONS", "INMEMORY GRAPH"]):
            raise ValueError(
                "must be one of enum values ('PARTITIONS', 'INMEMORY GRAPH')"
            )
        return value

    @field_validator("distance_metric")
    def distance_metric_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(
            [
                "COSINE",
                "MANHATTAN",
                "HAMMING",
                "JACCARD",
                "DOT",
                "EUCLIDEAN",
                "L2_SQUARED",
                "EUCLIDEAN_SQUARED",
            ]
        ):
            raise ValueError(
                "must be one of enum values ('COSINE', 'MANHATTAN', 'HAMMING', 'JACCARD', 'DOT', 'EUCLIDEAN', 'L2_SQUARED', 'EUCLIDEAN_SQUARED')"
            )
        return value

    @field_validator("quantization_type")
    def quantization_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["NONE", "SCALAR"]):
            raise ValueError("must be one of enum values ('NONE', 'SCALAR')")
        return value

    @field_validator("compression_ratio")
    def compression_ratio_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set([2, 4, 8]):
            raise ValueError("must be one of enum values (2, 4, 8)")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of VectorIndexParamsVectorIndexParams from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set(
            [
                "additional_properties",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of distribute_params
        if self.distribute_params:
            _dict["distribute_params"] = self.distribute_params.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if quantization_type (nullable) is None
        # and model_fields_set contains the field
        if (
            self.quantization_type is None
            and "quantization_type" in self.model_fields_set
        ):
            _dict["quantization_type"] = None

        # set to None if compression_ratio (nullable) is None
        # and model_fields_set contains the field
        if (
            self.compression_ratio is None
            and "compression_ratio" in self.model_fields_set
        ):
            _dict["compression_ratio"] = None

        # set to None if distribute_params (nullable) is None
        # and model_fields_set contains the field
        if (
            self.distribute_params is None
            and "distribute_params" in self.model_fields_set
        ):
            _dict["distribute_params"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of VectorIndexParamsVectorIndexParams from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        model_values: Dict[str, Any] = {}
        for field_name in (
            "auto_index",
            "organization",
            "distance_metric",
            "accuracy",
            "online_build",
            "quantization_type",
            "compression_ratio",
            "advanced_params",
        ):
            if field_name in obj:
                model_values[field_name] = obj.get(field_name)
        if "distribute_params" in obj:
            model_values["distribute_params"] = (
                VectorIndexParamsVectorIndexParamsDistributeParams.from_dict(
                    obj["distribute_params"]
                )
                if obj.get("distribute_params") is not None
                else None
            )

        _obj = cls.model_validate(model_values)
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj
